-- 코드를 입력하세요
SELECT
    FH.FLAVOR
FROM
    FIRST_HALF FH 
LEFT JOIN 
    JULY JL ON FH.FLAVOR = JL.FLAVOR
GROUP BY 
    FH.FLAVOR
ORDER BY 
    (FH.TOTAL_ORDER + SUM(JL.TOTAL_ORDER)) DESC
LIMIT 
    3;